CREATE TABLE Users (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
);

CREATE TABLE Posts (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  title VARCHAR(32) NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY fk_userid(user_id) 
  REFERENCES Users (id)
  ON DELETE RESTRICT ON UPDATE RESTRICT
);
